version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel12-dev-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
      - node
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: laravel12-dev-db
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - dbdata-dev:/var/lib/mysql

  node:
    image: node:20
    container_name: laravel12-dev-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

volumes:
  dbdata-dev:
